# Generated by Django 5.2.7 on 2025-10-27 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstProject', '0003_student_studentprofile_subjectreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemodel',
            options={'ordering': ['-date_time'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-time_created'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='subjectreview',
            options={'ordering': ['-date_time'], 'verbose_name': 'Subject Review', 'verbose_name_plural': 'Subject Reviews'},
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Subject Image'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='type',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('WD', 'Web Development')], default='AI', max_length=2, verbose_name='Subject Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='MyFirstProject.samplemodel', verbose_name='Enrolled Courses'),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_number',
            field=models.IntegerField(unique=True, verbose_name='Profile Number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='MyFirstProject.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Profile Created'),
        ),
        migrations.AlterField(
            model_name='subjectreview',
            name='comment',
            field=models.TextField(verbose_name='Review Comment'),
        ),
        migrations.AlterField(
            model_name='subjectreview',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='subjectreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='subjectreview',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MyFirstProject.samplemodel', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='subjectreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectreview',
            unique_together={('subject', 'user')},
        ),
    ]
